disabled_rules:
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  - modifier_order
  - multiline_arguments
  - operator_usage_whitespace
  # Find all the available rules by running:
  # swiftlint rules
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

excluded:
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 200
# they can set both implicitly with an array
function_body_length:
  warning: 30 # warning
  error: 40 # error
type_body_length:
  warning: 90 # warning
  error: 110 # error
# or they can set both explicitly
file_length:
  warning: 200
  error: 240
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - API
    - key
    - UK
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)